# Generated by Django 5.2.1 on 2025-05-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiler_app', '0007_remove_project_image_project_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
