# Generated by Django 5.2.1 on 2025-05-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiler_app', '0008_project_file2'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file2_is_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='file_is_img',
            field=models.BooleanField(default=True),
        ),
    ]
