# Generated by Django 5.2.1 on 2025-05-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiler_app', '0009_project_file2_is_image_project_file_is_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='file2_is_image',
        ),
        migrations.AddField(
            model_name='project',
            name='file2_is_img',
            field=models.BooleanField(default=True),
        ),
    ]
